server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    
    # Конфигурация для SPA (Single Page Application):
    # Если запрошенный URI ($uri) не является существующим файлом или папкой ($uri/),
    # запрос передается файлу index.html, который обрабатывает маршрутизацию на стороне клиента.
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Запрет доступа к скрытым файлам
    location ~ /\. {
        deny all;
    }
}
